---
- hosts: all

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
      tags:
        - ping

    - name: Print welcome message
      ansible.builtin.debug:
        msg: "Hello world!"
      tags:
        - message
